import type { ConversationSummaryConfig } from "@/common/types";
import {
  CONVERSATION_SUMMARY_ENABLED_DEFAULT,
  CONVERSATION_SUMMARY_KEEP_MESSAGES_DEFAULT,
  CONVERSATION_SUMMARY_KEEP_TOKENS_DEFAULT,
  CONVERSATION_SUMMARY_MIN_RECENT_MESSAGES_DEFAULT,
  CONVERSATION_SUMMARY_MAX_CHARS_DEFAULT,
  CONVERSATION_SUMMARY_MODE_DEFAULT,
  CONVERSATION_SUMMARY_TRIGGER_MESSAGES_DEFAULT,
  CONVERSATION_SUMMARY_TRIGGER_TOKENS_DEFAULT,
} from "@/common/constants";

export const DEFAULT_CONVERSATION_SUMMARY_CONFIG: ConversationSummaryConfig = {
  enabled: CONVERSATION_SUMMARY_ENABLED_DEFAULT,
  maxChars: CONVERSATION_SUMMARY_MAX_CHARS_DEFAULT,
  mode: CONVERSATION_SUMMARY_MODE_DEFAULT,
  summaryTriggerTokens: CONVERSATION_SUMMARY_TRIGGER_TOKENS_DEFAULT,
  summaryKeepTokens: CONVERSATION_SUMMARY_KEEP_TOKENS_DEFAULT,
  summaryTriggerMessages: CONVERSATION_SUMMARY_TRIGGER_MESSAGES_DEFAULT,
  summaryKeepMessages: CONVERSATION_SUMMARY_KEEP_MESSAGES_DEFAULT,
  summaryMinRecentMessages: CONVERSATION_SUMMARY_MIN_RECENT_MESSAGES_DEFAULT,
};
